# -*- coding: utf-8 -*-
"""Python_Project_visualizations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11KBkiJ9180V5lsPP3O-NNI9liyb3FwA9

# Part 1a: Data Wrangling
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

#load data and inspection
data=pd.read_csv('/content/country_wise_latest.csv')

#Initial Observations
data.head()
data.info()
data.describe()

#Data Cleaning
data.dropna(inplace=True)

#Data with WHO region aggregation
data_region = data.groupby('WHO Region').agg({
    'Confirmed': 'sum',
    'Deaths': 'sum',
    'Recovered': 'sum',
    'Active': 'sum',
    'New cases': 'sum',
    'New deaths': 'sum',
    'New recovered': 'sum'
}).reset_index()

# Calculate rates after aggregation
data_region['Case_Fatality_Rate'] = (data_region['Deaths'] / data_region['Confirmed'] * 100).round(2)
data_region['Recovery_Rate'] = (data_region['Recovered'] / data_region['Confirmed'] * 100).round(2)
data_region.head()

#Save to csv
data_region.to_csv('data_region.csv', index=False)

# Data without WHO aggregation

#Case Fatality Rate (CFR)
data['Case_Fatality_Rate']=(data['Deaths']/data['Confirmed']*100).round(2)
data.head()

#Recovery Rate
data['Recovery_Rate']=(data['Recovered']/data['Confirmed']*100).round(2)
data.head()


#Selecting Relevant columns
data=data[['Country/Region','Confirmed','Deaths','Recovered','Active','Case_Fatality_Rate','Recovery_Rate','New deaths','New cases','New recovered','WHO Region']]
data.head()

#save to csv
data.to_csv('data_without_region_agg.csv',index=False)

"""# Part 2: Data Visualization with Matplotlib and Seaborn"""

#Line chart: Top 5 countries deaths over confirmed cases (hint: use Pandas nlargest)
top_deaths=data.nlargest(5,'Deaths')
print(top_deaths)
plt.figure(figsize=(10, 6))
plt.plot(top_deaths['Country/Region'], top_deaths['Deaths'],
         marker='o', linewidth=2, markersize=10, color='red')
plt.xlabel('Country', fontsize=20)
plt.ylabel('Deaths', fontsize=20)
plt.title('Top 5 Countries by Death Count', fontsize=20, fontweight='bold')
plt.xticks(rotation=45, ha='right',fontsize=15)
plt.yticks(fontsize=15)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

#Scatter plot: Confirmed vs. Deaths with WHO Region colors

plt.figure(figsize=(10, 6))
sns.scatterplot(data=data, x='Confirmed', y='Deaths', hue='WHO Region', palette='viridis',s=200)
plt.xlabel('Confirmed', fontsize=20)
plt.ylabel('Deaths', fontsize=20)
plt.title('Confirmed vs. Deaths with WHO Region Colors', fontsize=20, fontweight='bold')
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.legend(fontsize=15)
plt.grid(True, alpha=0.3)

#Bar chart: Top 10 countries by recovery rate (hint: use Pandas nlargest)
top_recovery=data.nlargest(10,'Recovery_Rate')
plt.figure(figsize=(10, 6))
sns.barplot(data=top_recovery, x='Country/Region', y='Recovery_Rate', palette='viridis',hue='Country/Region')
plt.xlabel('Country', fontsize=20)
plt.ylabel('Recovery Rate', fontsize=20)
plt.xticks(rotation=45, ha='right',fontsize=15)
plt.yticks(fontsize=15)
plt.title('Top 10 Countries by Recovery Rate', fontsize=20, fontweight='bold')

#Box plot: Deaths distribution by WHO Region
plt.figure(figsize=(12, 8))
sns.boxplot(x='WHO Region', y='Case_Fatality_Rate', data=data,palette='viridis',hue='WHO Region')
plt.title('Box Plot of Case Fatality Rate (CFR) by WHO Region',fontsize=15)
plt.ylabel('Case Fatality Rate (CFR) %',fontsize=15)
plt.xlabel('WHO Region')
plt.xticks(rotation=45, ha='right',fontsize=15)
plt

#Faceted plot: New cases vs New deaths by region
p = sns.FacetGrid(data=data, col='WHO Region', col_wrap=3, height=4,palette="viridis",hue='WHO Region')
p.fig.suptitle('New Cases vs New Deaths by Region', fontsize=20, fontweight='bold',y=1.02)
p.map(plt.scatter, 'New cases', 'New deaths', alpha=0.6,s=200)
p.set_titles("{col_name}", fontsize=12, fontweight='bold')
p.set_axis_labels('New Cases', 'New Deaths')
p.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
sns.kdeplot(data=data, x='Case_Fatality_Rate', hue='WHO Region', fill=True, alpha=0.3,palette="viridis")
plt.xlabel('Case Fatality Rate (%)', fontsize=12, fontweight='bold')
plt.ylabel('Density', fontsize=12, fontweight='bold')
plt.title('Distribution of Case Fatality Rates by WHO Region', fontsize=14, fontweight='bold')
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""# Part 3: Interactive Visualizations with Plotly"""

import plotly.express as px

#Interactive Line Plot
fig=px.line(top_deaths,y='Deaths',x='Country/Region',title='Top 5 Countries by Deaths',markers=True,
            hover_data={
                'Case_Fatality_Rate': ':.2f',
                'Confirmed': True
            })
fig.update_layout(xaxis_title='Country',yaxis_title='Deaths',xaxis_tickangle=-45)
fig.show()

#Interactive Facet Plot
fig = px.scatter(data, x='New cases', y='New deaths',
                 facet_col='WHO Region', facet_col_wrap=3,
                 color='WHO Region',
                 hover_name='Country/Region',
                 title='New Cases vs New Deaths by Region')
fig.update_traces(marker=dict(size=10, opacity=0.6))
fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))  # Clean titles
fig.update_layout(showlegend=True, font=dict(size=12))

fig.show()